;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dabbrev-expand
        electric-newline-and-maybe-indent
        end-of-buffer
        eval-last-sexp
        eval-print-last-sexp
        ignore
        indent-for-tab-command
        kill-region
        markdown-outdent-or-delete
        org-end-of-line
        org-return
        org-self-insert-command
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        helm-confirm-and-exit-minibuffer
        help-for-help
        mouse-set-region
        pytest-again
        realgud:cmd-continue
        ))
