;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        dabbrev-expand
        electric-newline-and-maybe-indent
        end-of-buffer
        eval-last-sexp
        eval-print-last-sexp
        ignore
        indent-for-tab-command
        kill-region
        lsp-signature-stop
        markdown-enter-key
        markdown-outdent-or-delete
        org-beginning-of-line
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-return
        org-self-insert-command
        org-yank
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        helm-confirm-and-exit-minibuffer
        help-for-help
        lsp-ui-doc--handle-mouse-movement
        mac-mwheel-scroll
        mouse-set-region
        pytest-again
        realgud:cmd-continue
        suspend-frame
        ))
