(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "overseer")
(depends-on "f")

(depends-on "shell-pop")
(depends-on "circe")
(depends-on "virtualenvwrapper")
(depends-on "magit")
(depends-on "git-gutter")
(depends-on "rich-minority")
(depends-on "projectile")
(depends-on "helm")
(depends-on "helm-projectile")

(depends-on "web-mode")
(depends-on "haskell-mode")
(depends-on "groovy-mode")
(depends-on "yaml-mode")
(depends-on "typescript-mode")
(depends-on "tide")

(depends-on "flycheck")
(depends-on "company")
(depends-on "company-jedi")
